### ISSUE TITLE
Building Clp to DLL

### ISSUE THREAD

**Issue by framlingham** [coin-or/Clp#101]
Dear Clp maintainers - I have made Clp build a DLL on windows, and added a couple of functions to the C interface - but I made all the changes on the SVN repository I found first (https://projects.coin-or.org/svn/Clp/stable/1.17/Clp). I'd like to contribute the code, so I've attached a unified diff of what I did. Please put it under your existing licence, and my boss says contributing the code would be excellent.

[libClp to build DLL.zip](https://github.com/coin-or/Clp/files/3041667/libClp.to.build.DLL.zip)

**Comment by svigerske** [comment]
I committed the changes to the C interface with 9d12ebe (r2441).

@jjhforrest There is also this change proposed:
```patch
Index: src/ClpModel.cpp
===================================================================
--- src/ClpModel.cpp	(revision 2405)
+++ src/ClpModel.cpp	(working copy)
@@ -375,8 +375,10 @@
   gutsOfLoadModel(numrows, numcols,
     collb, colub, obj, rowlb, rowub, rowObjective);
   CoinBigIndex numberElements = start ? start[numcols] : 0;
-  CoinPackedMatrix matrix(true, numrows, numrows ? numcols : 0, numberElements,
+  CoinPackedMatrix matrix(true, numrows, numcols, numberElements,
     value, index, start, NULL);
   matrix_ = new ClpPackedMatrix(matrix);
   matrix_->setDimensions(numberRows_, numberColumns_);
 }
```
This reverts a change you did in 58cf499a and I don't know what the reason is to change this back.

The diff by @framlingham also brings many changes to MSVS project files for v10 and v14. I don't want to touch these.

**Comment by framlingham** [comment]
Perhaps leave the v10 changes out, sorry about that. I would encourage you to allow the v14 changes, perhaps in a v15 folder, now that I look more into VS versions (https://stackoverflow.com/questions/44046355/visual-studio-2015-not-detecting-v141-2017-build-tools).

**Edit:** Hmm, it looks like perhaps I should put the changed vcxproj files into v15 folders as well.

**Comment by framlingham** [comment]
I'd also leave out the 58cf499 revert I left in, sorry about that - it looks like maybe there's an issue with `rows == 0` but `cols > 0`.

**Comment by svigerske** [comment]
I hardly care about these MSVC project files. They are quickly broken anyway since no Clp developer is using them. Thus, it probably doesn't matter much if more of them are lying around and so I've copied the v14 to v15 and added the changes there, as you suggested.
Note, that v14 was probably meant for MSVS 2015 and 2017 and there is no MSVC++ 15 yet (https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering).

@h-g-s If you care, maybe you want to have a look on this. If changes here didn't make sense, just revert/remove.

**Comment by tkralphs** [comment]
As long as older Visual Studio files continue to work and the upgrade to later versions continues to work with no issues, I would prefer to maintain just one set of Visual Studio files of some base version. I don't mind if the base version is later than the current v10, but this should be unified across all projects. Now we have v15 files for Clp, but not for the dependencies. At one point in time, I also put a lot of work into making these all use common property sheets. I wanted to make sure that these didn't get lost.

**Comment by framlingham** [comment]
Thank you! I'm happy to have a different folder name, but thanks!
