### ISSUE TITLE
make install -j N fails for N > 1

### ISSUE THREAD

**Issue by jamiesnape** [coin-or/Clp#109]
For example,
```
$ make install -j8
...
Error 1: mkdir: /usr/local/include/coin: File exists.
```

**Comment by tkralphs** [comment]
I assume you are doing a "monolithic" build (using the `configure` script in the root directory)? This is no longer the recommended way to build. In any case, I need more information to replicate. It works fine for me, but I guess you may be configuring with some additional options. Can you please send the complete set of commands needed to replicate and any additional information that might be relevant?

**Comment by jamiesnape** [comment]
For instance, the Homebrew formula that you maintain works around the same issue. Remove this line: https://github.com/coin-or-tools/homebrew-coinor/blob/905c05d2ce9050de59cb524aea938073349d2fb2/clp.rb#L74

**Comment by tkralphs** [comment]
OK, thanks, that helps. It's strange, doesn't seem to be an issue in general, just in homebrew.

**Comment by jamiesnape** [comment]
This reproduces the issue outside of homebrew:

```bash
#!/bin/bash

set -euxo pipefail

brew update
brew install gcc pkg-config

rm -rf /usr/local/Cellar/clp/1.17.3

pushd /tmp
curl -LO https://github.com/coin-or-tools/Data-Netlib/archive/releases/1.2.8.tar.gz
tar -xf 1.2.8.tar.gz
rm -f 1.2.8.tar.gz 
pushd Data-Netlib-releases-1.2.8
./configure --prefix=/usr/local/Cellar/clp/1.17.3
make install -j8
popd
rm -rf Data-Netlib-releases-1.2.8

curl -LO https://github.com/coin-or-tools/Data-Sample/archive/releases/1.2.11.tar.gz
tar -xf 1.2.11.tar.gz
rm -f 1.2.11.tar.gz
pushd Data-Sample-releases-1.2.11
./configure --prefix=/usr/local/Cellar/clp/1.17.3
make install -j8
popd
rm -rf Data-Sample-releases-1.2.11

curl -LO https://github.com/coin-or/CoinUtils/archive/releases/2.11.2.tar.gz
tar -xf 2.11.2.tar.gz
rm -f 2.11.2.tar.gz
pushd CoinUtils-releases-2.11.2
./configure --includedir=/usr/local/Cellar/clp/1.17.3/include/clp --prefix=/usr/local/Cellar/clp/1.17.3
make install -j8
popd
rm -rf CoinUtils-releases-2.11.2

curl -LO https://github.com/coin-or/Clp/archive/releases/1.17.3.tar.gz
tar -xf 1.17.3.tar.gz
rm -f 1.17.3.tar.gz
pushd Clp-releases-1.17.3
./configure --includedir=/usr/local/Cellar/clp/1.17.3/include/clp --prefix=/usr/local/Cellar/clp/1.17.3
make install -j8
popd
rm -rf Clp-releases-1.17.3
popd
```

**Comment by tkralphs** [comment]
OK, thanks, I will take a look.

**Comment by tkralphs** [comment]
I haven't been able to replicate this on either Linux or OS X. I ran the exact script above on my OS X box and had no problems. I ran a version of it on Linux (with different paths) and also had no problems. I guess it might be non-deterministic. I have seen occasional failures building multiple projects in parallel, but just re-starting the build always fixes it and I assumed that Make is just not correctly assessing dependencies. Can you replicate this reliably, is it still an issue?

**Comment by jamiesnape** [comment]
I can and yes, it is still an issue.

> I assumed that Make is just not correctly assessing dependencies.

Exactly. I imagine for certain values of `j` for a machine with `k` cores on OS `a` and compiler `b`, everything happens to get built before the install, so it works out fine. Unfortunately, I don't seem to be that lucky.

**Comment by tkralphs** [comment]
OK, but the dependencies are built in sequential order in your script so I assume that the problem is happening internal to one of the `make install` steps above. I just can't quite see how anything can be installed before everything is built in one of the steps above just by the basic logic of the Makefile. It also seems like doing
```
make -j8
make install -j8
```
would fix it. I'm not sure quite where to start with this. I've only observed something that could possibly be due to this issue a few times over a span of years and I build projects in parallel all the time.

**Comment by jamiesnape** [comment]
Depends how you define dependencies. I was assuming dependencies of the `install` target within a given call of `make`. Running `make` and `make install` separately would be a workaround.

**Comment by tkralphs** [comment]
Sorry if you already know this, but the `install` target in the `Makefile` is generated from the template `Makefile.in`, which is itself auto-generated based on specifications in `Makefile.am`. The only control we have over the `install` target and its dependencies is through the mechanism for specifying dependencies in `Makefile.am`. As far as I can see, those seem to be right, but obviously, we are missing something somewhere. 

Looking at the particular error you reported, I don't actually see how it could arise. 
```
$ make install -j8
...
Error 1: mkdir: /usr/local/include/coin: File exists.
```
`mkdir` (without `-p`) only appears in the generated `Makefile`s that I'm looking at in a very few places that would not be touched in your build scenario. This looks a bit like it is trying to create the directory <prefix>/include/coin, but the prefix you specify is always something like `/usr/local/Cellar/clp/1.17.3`, not `/usr/local`. And in any case, the directory <prefix>/include/coin would always be created with `mkdir -p`. The relevant target in the `Makefile` I'm looking at seems to be
```
install-includecoinHEADERS: $(includecoin_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(includecoindir)" || $(mkdir_p) "$(DESTDIR)$(includecoindir)"
...
```
I guess I could imagine that there could be multiple attempts to create this directory, but the `-p` should allow this. It would be really helpful if you could isolate this to one particular project. Since you see it reliably, anything more you can say about how/when it arises would be really helpful.

**Comment by tkralphs** [comment]
@svigerske Any ideas about this?

**Comment by tkralphs** [comment]
Well, strangely, it turns out that `mkdir -p` does return an error if the directory exists on OS X, in contrast to Linux, so this could be part of the issue. For this reason, it seems `mkdir_p` is defined to be `install-sh -d` on OS X. Perhaps we accidentally hard-coded a `mkdir -p` somewhere...

**Comment by svigerske** [comment]
> @svigerske Any ideas about this?

No, not really.
Doesn't seem like a serious problem (a number of workarounds are mentioned).
Further, a lot of information that could be useful has been replaced by "..." in the error report, so it's made very difficult to see what could be the problem.
Thus, to me this doesn't seem to be worth to spend time on this. The reporter could probably figure out what causes the problem by just digging into the Makefiles a bit more.

**Comment by jamiesnape** [comment]
> Thus, to me this doesn't seem to be worth to spend time on this. The reporter could probably figure out what causes the problem by just digging into the Makefiles a bit more.

Entirely your choice; your project. I am reporting this for the benefit of you and your other users. Sure it is only a minor annoyance for me, but it does not look great for future bug reporters to just palm it off and say workaround or fix it yourself. I think this actually affects some common COIN-OR build code, so most of your projects have this issue, not just Clp.

**Comment by tkralphs** [comment]
I'm willing to spend a little time on it, but I do need more information about when the error arises---which project and the full output if possible. Also, if you have some explanation for why it involves creation of a directory that shouldn't ever get created with the configure command you put in your test, that would be helpful. I guess if I just try this enough times, I may eventually see a failure, but you indicated, you could replicate reliably.

**Comment by tkralphs** [comment]
`mkdir -p` does seem to be one of the likely culprits in failures of parallel make, but I couldn't find any problems with it in our configuration so far. I at least have a thread to pull.

**Comment by tkralphs** [comment]
@svigerske There is a macro `AC_PROG_MKDIR_P` (https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Particular-Programs.html) for determining if there is a thread-safe `mkdir -p`, but we are not using it, as far as I can see. Nevertheless, `MKDIR_P` seems to be getting set somehow. Do you know anything about it?

**Comment by jamiesnape** [comment]
Another workaround appears to be to create `/usr/local/Cellar/clp/1.17.3/include/clp` in my script in advance, which suggests that maybe directory creation is guarded by whether the directory does not exist.

**Comment by jamiesnape** [comment]
This looks suspicious:

https://github.com/coin-or/Clp/blob/dbc98c487e34b76c35aaabfe7a419b508479e195/install-sh#L235-L247

Also:

```
$ grep -R "mkdir_p =" Clp-releases-1.17.3/Makefile
Clp-releases-1.17.3/Makefile:mkdir_p = $(install_sh) -d
```

**Comment by jamiesnape** [comment]
My guess would at the very least add `AC_PROG_MKDIR_P` to `configure.ac` and replace usages of `$(mkdir_p)` with `$(MKDIR_P)` per https://www.gnu.org/software/automake/manual/html_node/Obsolete-Macros.html and https://www.gnu.org/software/autoconf/manual/html_node/Particular-Programs.html. Then you quite possibly won't even need `install-sh` (you may need `AC_PROG_INSTALL` in `configure.ac`). Maybe even just removing `install-sh` is an option?

**Comment by svigerske** [comment]
> @svigerske There is a macro `AC_PROG_MKDIR_P` (https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Particular-Programs.html) for determining if there is a thread-safe `mkdir -p`, but we are not using it, as far as I can see. Nevertheless, `MKDIR_P` seems to be getting set somehow. Do you know anything about it?

That link says that with install-sh from autoconf before 2.60, there could be a race condition. We use autoconf 2.59. So that could be the cause here. Also I don't see a mention of MKDIR_P in Clp's configure, only mkdir_p.
In the branches that use current autotools, however, there is a MKDIR_P, so they should hopefully also have the improved install-sh.

AM_PROG_MKDIR_P or AC_PROG_MKDIR_P are invoked by the autoconf-macros that belong to libtool, so we don't need to use them explicitly in our configure.ac.

**Comment by jamiesnape** [comment]
Looks like `autoreconf --install` with new versions of the copied files (including `install-sh`) did indeed get me a version that works. That is autoconf 2.69 an `install-sh` version 2013-12-25.23.

**Comment by tkralphs** [comment]
Yeah, I just noticed the same thing. We are in the middle of updating our whole autoconf setup to the latest versions (we have been stuck on old versions for arcane reasons). I don't see any reason why we couldn't just replace `install-sh` in the meantime, but I guess it will be replaced when we finally upgrade in any case. @svigerske What do you think?

**Comment by svigerske** [comment]
I don't know what other effects it would have to use an install-sh from a much more recent autoconf version. As this issue here doesn't seem critical, I wouldn't do this.

**Comment by jamiesnape** [comment]
The API of the two is identical.

**Comment by jamiesnape** [comment]
And looking at the diff most of the changes are stylistic except fixing the race condition. Maybe you could upgrade to `install-sh` from 2.60 and there will be even fewer changes and still get the fix?

**Comment by jamiesnape** [comment]
(diff of install-sh from this repo (presumably 2.59) to 2.60 is here: https://gist.github.com/jamiesnape/31700a3b7dedbc89e46b6b5f5235dfc6)

**Comment by tkralphs** [comment]
Hmm, there do seem to be quite a few changes. @svigerske Let's talk about this off-line. If the new autotools setup is not far off, maybe better to wait for that, since there is a workaround for this at the moment.

**Comment by tkralphs** [comment]
It turns out that I was wrong about `mkdir -p` on OS X. The man page is worded a little strangely and I overlooked that it does say explicily that it doesn't return an error if the directory exists, so I'm still wondering how the error that was reported could possibly arise. It's also still a mystery why `install_sh -d` is used instead of `mkdir -p` on OS X. Either the behavior used to be different or there is another reason that `mkdir -p` is not thread-safe.

**Comment by svigerske** [comment]
master has been updated to use current autotools.
