### ISSUE TITLE
how does it work at windows

### ISSUE THREAD

**Issue by fveg66** [coin-or/Clp#123]
ı cant install the clp how can ı do that ı am trying to understand explanation.There is no exe file

**Comment by sschnug** [comment]
There are two places i know of, where binaries are available:

- https://ampl.com/products/solvers/open-source/
    - provides cbc, which is feature-wise a super-set of clp
    - should bring you whatever you want from clp

- https://bintray.com/coin-or/download/Clp#files
    - might need some additional mingw64 libraries (at least that's my observation)
        - either copy from your local mingw64 install or use within mingw64/msys2 shell

Apart from that, building on windows is doable (and not as hard as some other CoinOR libs).

This repository has a linked CI-pipeline where you can learn from: 

- https://ci.appveyor.com/project/tkralphs/clp-m0kud
    - mingw64 based and microsoft visual studio based flavours are available

And there is also:

-  https://github.com/coin-or/coinbrew
    - does work within mingw64 (for me)
    - but setting everything up is still no fun

Try the binaries first to evaluate if it's what you are looking for.

**Comment by tkralphs** [comment]
Thanks @sschnug for the summary. The binaries at https://bintray.com/coin-or/download/Clp#files now do include the DLLs, so you shouldn't need to have MSys2 installed anymore to use them. Note, however, that thsi is only currently true for the master branch builds.

For building from source, the instructions at https://coin-or.github.io/user_introduction#windows-1 are now pretty detailed and should make the build process straightforward.

I'm closing this issue for now, since I guess the question should be answered.
