### ISSUE TITLE
Clp_C_Interface.h function declaration

### ISSUE THREAD

**Issue by jpbrooks** [coin-or/Clp#278]
When compiling my R library that uses Clp, there is a warning issued: "function declaration isn't a prototype".  The output is here: [https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/pcaL1-00check.html](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/pcaL1-00check.html)
and with a link to the install log here: [https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/pcaL1-00install.html](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/pcaL1-00install.html)

**Comment by tkralphs** [comment]
This is apparently because `ClpSolve_new()` should be declared as `ClpSolve_new(void)` to indicate it takes no arguments. This is done for other functions with no arguments, but not this one for some reason. I guess it is a harmless warning, but I fixed it in `stable/1.17` and it will eventually make it out into release. Be aware, though, that you seem to be using `stable/1.16`, which is an older stable, from the line number.
